# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 15
  username: <%= Rails.application.credentials[:DB_USER] %>
  password: <%= Rails.application.credentials[:DB_PASS] %>
  host: <%= Rails.application.credentials[:DB_HOST] %>

default: &default_replica
  adapter: mysql2
  encoding: utf8mb4
  pool: 15
  username: <%= Rails.application.credentials[:DB_USER] %>
  password: <%= Rails.application.credentials[:DB_PASS] %>
  host: <%= Rails.application.credentials[:DB_HOST_REPLICA] %>



development:
  primary:
    <<: *default
    database: IRM_development
    password: Root1234$
  primary_replica:
    <<: *default_replica
    database: IRM_development
    database_tasks: false
    password: Root1234$


staging:
  primary:
    <<: *default
    database: IRM_staging
  primary_replica:
    <<: *default_replica
    database: IRM_staging
    database_tasks: false


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  adapter: sqlite3
  pool: 15
  timeout: 10000
  database: tmp/test.sqlite3<%= ENV['TEST_ENV_NUMBER'] %>
  # database: ":memory:" # Use an in-memory database

test2: &test
  <<: *default
  database: IRM_test<%= ENV['TEST_ENV_NUMBER'] %>


# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary:
    <<: *default
    database: IRM_production
  primary_replica:
    <<: *default_replica
    database: IRM_production
    database_tasks: false


cucumber:
  <<: *test